ALTER TABLE app.users
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN sex DROP DEFAULT,
    ALTER COLUMN weight_grams SET NOT NULL,
    ALTER COLUMN birth_date SET NOT NULL,
    ALTER COLUMN height_cm SET NOT NULL;
